title: <img src="./logo.svg" alt="LoAT">
email: florian.frohn@cs.rwth-aachen.de
description: >- # this means to ignore newlines until "baseurl:"
  We propose a novel acceleration technique for loops operating
  on arrays. The goal of acceleration is to characterize the transitive closure
  of loops in a logic which is suitable for automated reasoning. Using the
  new notion of inductive lvalues, our technique can handle loops where
  previous techniques fail, and it unifies acceleration for arrays and scalar
  variables by regarding scalars as arrays of dimension 0. Moreover, our
  approach uses Î»s instead of quantifiers. Then the resulting SMT problems
  can be solved via lemmas on demand. An empirical evaluation of our
  implementation in the tool LoAT shows the power of our approach.
github_username:  ffrohn
theme: jekyll-theme-cayman
github:
  is_project_page: false